### PR TITLE
remove implicit dependency on ~/.aws/credentials

### PR DESCRIPTION
**Pull request by git-phu**
with this change awsprocesscreds no longer needs a default profile with
access keys present in ~/.aws/credentials in order to run

this allows your default profile to use awsprocesscreds instead of
access keys

### CODE REVIEW

**Review by joshk0 — COMMENTED** [review]
This one is good for merging upstream as-is.
tho, do the unit tests pass with this change?

**Comment by git-phu** [comment]
They passed on the upstream pr awslabs/awsprocesscreds#20

**Comment by git-phu** [comment]
good to merge here? Doesn't look like there's much activity upstream

**Comment by joshk0** [comment]
:shipit:

**Comment by git-phu** [comment]
thanks for review!

**Pull request merged**
