### PR TITLE
 support RelayState parameter for okta

### PR DESCRIPTION
**Pull request by git-phu**
RelayState is particularly useful for federated okta setups where the
end user has to log into okta instance 1, log into okta instance 2
through okta instance 1, then log into aws through okta instance 2
https://saml-doc.okta.com/SAML_Docs/Configure-SAML-2.0-for-Org2Org.html

### CODE REVIEW

**Comment by joshk0** [comment]
Looks good for internal consumption. :shipit:

For upstream submission, I would squash your commits and my commits together. You can take the credit, you did most of the real work! It's confusing to leave them as is since i made changes on top of your original ones.

It is likely to be the case that we do maintain this fork long term though, in which case the cleanliness of the commits matters less; but it also is better that our fork contains the same commit history as the PR which we are submitting upstream, so it might be worth doing now. /shrug !

**Review by joshk0 — APPROVED** [review]

**Comment by git-phu** [comment]
I think what I'll do here (also what I've done in the past for forks) is merge our changes as is, and if the upstream ever pulls this change in, then I'll basically force push the upstream master to this repo's master (possibly rebasing any other changes we have that are not upstream).  So I can submit the upstream pr as one commit, and then blow away these individual commits later on. Let me know though if that sounds crazy to you.

**Comment by joshk0** [comment]
What if you PR this change to @philip-linaro, he can add it to his upstream PR that already exists and then we can leave it to him to communicate with upstream?

Meanwhile both changes (upstream PR plus this one) should go into LiveRamp:master and be our working version until upstream starts looking at things that people do for them lol

**Comment by git-phu** [comment]
yeah sounds good haha

**Pull request merged**
